# Generated by Django 2.0.5 on 2018-06-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180629_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Document'),
        ),
    ]
